---
# handlers file for web
- name: Handler-One
  ansible.builtin.template:
    src: '{{ template_name }}'
    dest: /var/www/html/
  changed_when: true
  notify: Handler-Three
- name: Handler-Two
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: /var/www/html/
  loop: '{{ files }}'
  changed_when: true
  notify: Handler-Three
- name: Handler-Three
  ansible.builtin.service:
    name: '{{ package_name }}'
    state: restarted
